name: Build MdgWa

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and test app
      run: |
        ./gradlew assembleDebug
        ./gradlew connectedDebugAndroidTest
        
    - name: Generate Release Tag
      uses: amitsingh-007/next-release-tag@v5.1.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          generateReleaseNotes: true
          makeLatest: true
          artifacts: "app/build/outputs/apk/debug/,app/build/outputs/apk/debug/app-debug.apk"
