name: Build MdgWa

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and test app
      run: |
        ./gradlew assembleDebug
        ./gradlew connectedDebugAndroidTest
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          tag: ${{ steps.date.outputs.date }}
          makeLatest: true
          artifacts: "app/build/outputs/apk/debug/,app/build/outputs/apk/debug/app-debug.apk"
