name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
    - name: set up JDK 17
=======
    - name: set up JDK 21
>>>>>>> main
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and test app
      run: |
        ./gradlew assembleDebug
        ./gradlew connectedDebugAndroidTest

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/
